### ISSUE TITLE
Brain Storming Architecture

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#3]
Gather Information about available technologies and their usage.

**Comment by fhilgers** [comment]
# Draft

TODO diagram

We split the project into 4 parts:

1. Ebpf Programs
2. Ebpf Loader
3. Client library
4. Frontend

In this context, each part is mostly independent and only couples to their adjacent parts.

# How did we get here?

In the simplest form, we could run everything in a single app, however there are multiple reasons that speak against that:

- only ebpf needs root: running everything under root would leave us with a massive attack surface
- splitting work into teams: splitting forces us to define clear boundaries and make the teams more independent
- testing: separation forces us to use interfaces from the start so we do not end up in mocking hell. Also it makes finding the error in failing tests easier and speets up the test execution via caching.

# Why exactly these four parts and not something else?

## Ebpf Programs

Ebpf Programs require a very different style of programming (sandboxed, kernelspace) compared to userspace aplication. They have a well defined API anyway (maps).

## Ebpf Loader

This is basically the bridge between kernelspace and the API for consumers. It should alllow for controlling what happens regarding the ebpf programs (loading, unloading, rules, policies) and exporting data. Processing further should be kept to a minimum to reduce the attack surfice as this process runs as root. It should however allow processing to reduce IPC bandwidth. (Future: maybe processing via a wasm)

## Client library

This should be the library to control the ebpf loader and export data. The transport should be secured via certificates. This does not run as root. It can be used by the frontend app directly, but can also be used in the future to send events to a remote. It can also be used to process data further before sending it over a slower channel. One could for example use this library to build a service configured locally that sends data in the opentelemetry format to a vector instance ...

## Android App

This is the simplest way to control the daemon and display events locally on device. As the client libary is completely decoupled, we can create viewmodels on top of interfaces and test them in isolation.

# Specifics

- aya
- aidl (binder)
- tonic (grpc)
- uniffi (kotlin binding)
- jetpack compose

## Why aya

While ebpf programs could be written in C, we would most likely have to use C++ for loading them on android. Cross compiling, dependencies, safe code, etc. is way harder with c++, especially if most of the team has little to no prior knowledge. 

Rust has a toolchain manager (rustup), a build system (cargo), a dependency registry (crates.io) all builtin.

It allows us to use a single language, that can be easiliy cross compiled for android, has convenience libraries for binding generation to other languages like kotlin, has interop with c, c++ and java if necessary and even allows us to write eblf programs itself with little to no setup.

## aidl (binder)

In the android context, this is the recommended way to define apis between processes. It handles permissions and can be configured to only allow access between apps signed with the same key, which would be important for securing our eblf loader from unauthorized access.

However, there are some drawbacks for development and testing:

- if our loader runs as root, our app has no access to it, because apps cannot themselves run as root. Also, using the service registry is not possible, without hacks (ndk stub with a modified header or java reflection) as it is not a public api in the sdk
- tests have to run on android, because binder is android specific
- no streaming rpc (events should most likely be streamed)

We can remedy all three by using another form of rpc together with binder for initiating the connection in secure production environment.

## Grpc

Grpc is well established, offers streaming and protobuf messages are smaller in size than for example json. There is a server and client implementation in rust and it is also the default rpc for many existing telemetry collectors (opentelemetry). 

For testing we can just bind to a port with access for everyone and call the api from the all.

For production we create a ParcelFileDescriptor (unix domain socket) pair which is shared via a secure binder ipc.

This allows to run almos all tests under a generic linux runner instead of android emulators but still keeps the security of traditional binder ipc with selinux policies.

## uniffi

A library by mozilla: Basically creates kotlin binding and more from rust. Has suppor for trats (interfaces) and async/suspend.

## Jetpack Compose

Enjoyable android app development compared to juggling xml files.

# Summary

- Ebpf programs define their api via maps
- Ebpf loader configures ebpf programs and exports the data with as little attack surface as possible while being root
- Client library is the entrypoint to ebpf, controls and collects data, building block for other applications that need the data
- Android app is one such application that acts like a showcase for the whole system with controlling what to collect and then visualizing it

**Comment by fhilgers** [comment]
Superseded by #34
